console.time();
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.log("Hola como estas amigo");
console.timeEnd();